application: irssinotifierwp
version: 1
runtime: java

handlers:
- url: /client/login
  servlet: com.tol1.irssinotifier.server.LoginUser
  
- url: /client/login/loginsuccess
  servlet: com.tol1.irssinotifier.server.LoginSuccess
  
- url: /client/register
  servlet: com.tol1.irssinotifier.server.RegisterPhoneClient
  
- url: /API/Message
  servlet: com.tol1.irssinotifier.server.MessageHandler